services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD : postgres
      POSTGRES_USER : postgres
      POSTGRES_DB : postgres
    ports:
    - "5434:5432"
    volumes:
    - db_data:/var/lib/postgresql/data

volumes:
 db_data: